version: 2
sources: # sources tells dbt these are raw tables
  - name: raw_tpch # a name references this group of tables
    description: source tpch data
    database: snowflake_sample_data # raw tables database name 
    schema: tpch_sf1 # raw tables schema name
    tables:
      - name: orders # raw table name
        description: main order tracking table
      - name: lineitem
        description: main lineitem table